#include<stdio.h>
#include<stdlib.h>

  //VARIAVEIS GLOBAIS
  //A VARIAVEL CAMPO REPRESENTA A INTERFACE DO CAMPO MINADO, O CAMPO QUE É MOSTRADO AO USUÁRIO
  //A VARIAVEL OP, REPRESENTA A MATRIZ DE OPERAÇÕES, REPRESENTAÇÕES DAS BOMBAS, DICAS E ESPAÇOS VAZIOS DO CAMPO MINADO
  //COUNTBOMBAS TEM COMO VALOR DE CADA POSIÇÃO, A DICA DE UMA DETERMINADA POSIÇÃO NA MATRIZ OP
  //ESPACOSFREE REPRESENTA QUANTOS ESPAÇOS JA FORAM ABERTOS, SE BATER 75, O USUARIO VENCE O JOGO
  int campo[10][10], op[10][10], countbombas[100], espacosfree = 0;
  //VARIAVEIS UTILIZADAS NAS FUNÇÕES DE THREADS, MUTEX_BOMBA É A REGIÃO CRITICA E A BOMBA_ID AS THREADS
  pthread_mutex_t mutex_bomba[25];
  pthread_t bomba_id[25];

  //FUNÇÃO QUE RECEBE COMO PARAMETRO UMA POSIÇÃO NA MATRIZ DE OPERAÇÃO E ANALISA SE O VALOR É -1, QUE REPRESENTA
  //A BOMBA, CASO SIM, RETORNA 1, CASO NÃO, RETORNA 0;
  int verificaBomba(int linha, int coluna);

  //IMPRIME A MATRIZ DE INTERFACE EM SEU ESTADO INICIAL, OU SEJA, O CAMPO MINADO INICIAL
  void imprime_inicio();

  //FUNÇÃO QUE BLOQUEIA O ACESSO À REGIÃO CRITICA
  void gerando(int * bomba);

  //FUNÇÃO QUE LIBERA O ACESSO À REGIÃO CRÍTICA
  void acabou_gerar(int * bomba);

  //FUNÇÃO QUE UTILIZA THREADS PARA GERAR 25 BOMBAS SIMUTANEAMENTE
  void * gera_bombas(void *var);

  //FUNÇÃO QUE ANALISA AONDE TEM BOMBAS NA MATRIZ DE OPERAÇÃO E COLOCA AS DICAS AO REDOR DELAS
  void gera_dicas(void);

  //FUNÇÃO QUE ATUALIZA A MATRIZ DE OPERAÇÃO JÁ COM AS DICAS E AS BOMBAS ADICIONADAS
  void atualiza_op(void);

  //FUNÇÃO RECURSIVA QUE LIBERA OS ESPAÇOS VAZIOS INTERLIGADOS ATÉ ENCONTRAR UMA DICA
  void libera_vazio(int auxi, int auxj);

  //FUNÇÃO DA JOGADA DO USUÁRIO, VERIFICA O QUE O USUÁRIO ACERTOU, SE FOI UMA BOMBA, UM ESPAÇO VAZIO OU UMA DICA, E DEFINE
  //SE ELE PERDEU OU VENCEU O JOGO
  void verifica_vizinhanca();
